api:
  prefix: "/api/chatbot"

is_test_mode: true

llm:
  model_path: "api/models/mistral/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  max_tokens: 512
  context_length: 2048
  threads: 8
  gpu_layers: 0
  verbose: false

retrieval:
  embedding_model_name: "sentence-transformers/all-MiniLM-L6-v2"
  top_k: 3
  empty_context_message: "No context available."

cors:
  allowed_origins:
    - "*"
